use crate::constants::{
    area_names::{
        ARCANE_2, BAAL_5, BARRICADE_5, CATACOMBS_1, CATHEDRAL_1, CAVE_1, COURTYARD_1, CRYPT_1,
        DESERT_2, DUNGEON_3, HAREM_2, ICE_5, JAIL_1, JUNGLE_3, KURAST_3, LAIR_2, LAVA_4, LAVA_5,
        MESA_4, SEWER_2, SPIDER_3, TEMPLE_5, TOMB_2, TOWN_1, TOWN_2, TOWN_3, TOWN_4, TRISTRAM_1,
        WILDERNESS_1,
    },
    zone_names::{
        ABADDON, ANCIENT_TUNNELS, ARCANE_SANCTUARY, ARREAT_PLATEAU, BARRACKS, BLACK_MARSH,
        BLOODY_FOOTHILLS, BLOOD_MOOR, BURIAL_GROUNDS, CANYON_OF_THE_MAGI, CATACOMBS_LEVEL_1,
        CATACOMBS_LEVEL_2, CATACOMBS_LEVEL_3, CATACOMBS_LEVEL_4, CATHEDRAL, CAVE_LEVEL_1,
        CAVE_LEVEL_2, CITY_OF_THE_DAMNED, CLAW_VIPER_TEMPLE_LEVEL_1, CLAW_VIPER_TEMPLE_LEVEL_2,
        COLD_PLAINS, CRYSTALLINE_PASSAGE, DARK_WOOD, DEN_OF_EVIL, DISUSED_FANE, DISUSED_RELIQUARY,
        DRIFTER_CAVERN, DRY_HILLS, DURANCE_OF_HATE_LEVEL_1, DURANCE_OF_HATE_LEVEL_2,
        DURANCE_OF_HATE_LEVEL_3, FAR_OASIS, FLAYER_DUNGEON_LEVEL_1, FLAYER_DUNGEON_LEVEL_2,
        FLAYER_DUNGEON_LEVEL_3, FLAYER_JUNGLE, FORGOTTEN_RELIQUARY, FORGOTTEN_TEMPLE,
        FORGOTTEN_TOWER, FRIGID_HIGHLANDS, FROZEN_RIVER, FROZEN_TUNDRA, GLACIAL_TRAIL, GREAT_MARSH,
        HALLS_OF_ANGUISH, HALLS_OF_PAIN, HALLS_OF_THE_DEAD_LEVEL_1, HALLS_OF_THE_DEAD_LEVEL_2,
        HALLS_OF_THE_DEAD_LEVEL_3, HALLS_OF_VAUGHT, HAREM_LEVEL_1, HAREM_LEVEL_2, HOLE_LEVEL_1,
        HOLE_LEVEL_2, INFERNAL_PIT, INNER_CLOISTER, JAIL_LEVEL_1, JAIL_LEVEL_2, JAIL_LEVEL_3,
        KURAST_BAZAAR, KURAST_CAUSEWAY, KURAST_DOCKS, LOST_CITY, LOWER_KURAST, LUT_GHOLEIN,
        MAGGOT_LAIR_LEVEL_1, MAGGOT_LAIR_LEVEL_2, MAGGOT_LAIR_LEVEL_3, MAUSOLEUM, MONASTERY_GATE,
        NIHLATHAKS_TEMPLE, OUTER_CLOISTER, OUTER_STEPPES, PALACE_CELLAR_LEVEL_1,
        PALACE_CELLAR_LEVEL_2, PALACE_CELLAR_LEVEL_3, PIT_LEVEL_1, PIT_LEVEL_2, PIT_OF_ACHERON,
        PLAINS_OF_DESPAIR, RIVER_OF_FLAME, ROCKY_WASTE, ROGUE_ENCAMPMENT, RUINED_FANE,
        RUINED_TEMPLE, SEWERS_LEVEL_1, SEWERS_LEVEL_2, SEWERS_LEVEL_3, SPIDER_CAVE, SPIDER_CAVERN,
        SPIDER_FOREST, STONY_FIELD, STONY_TOMB_LEVEL_1, STONY_TOMB_LEVEL_2, SWAMPY_PIT_LEVEL_1,
        SWAMPY_PIT_LEVEL_2, SWAMPY_PIT_LEVEL_3, TAL_RASHA_S_CHAMBER, TAL_RASHA_S_TOMB,
        TAMOE_HIGHLAND, THE_ANCIENTS_WAY, THE_CHAOS_SANCTUARY, THE_PANDEMONIUM_FORTRESS,
        THE_SECRET_COW_LEVEL, THRONE_OF_DESTRUCTION, TOWER_CELLAR_LEVEL_1, TOWER_CELLAR_LEVEL_2,
        TOWER_CELLAR_LEVEL_3, TOWER_CELLAR_LEVEL_4, TOWER_CELLAR_LEVEL_5, TRAVINCAL, TRISTRAM,
        UNDERGROUND_PASSAGE_LEVEL_1, UNDERGROUND_PASSAGE_LEVEL_2, UPPER_KURAST, VALLEY_OF_SNAKES,
        WORLDSTONE_CHAMBER, WORLDSTONE_KEEP_LEVEL_1, WORLDSTONE_KEEP_LEVEL_2,
        WORLDSTONE_KEEP_LEVEL_3,
    },
};

pub fn zone_to_area(zone: &str) -> String {
    match zone {
        ROGUE_ENCAMPMENT => TOWN_1,
        BLOOD_MOOR | COLD_PLAINS | STONY_FIELD | DARK_WOOD | BLACK_MARSH | TAMOE_HIGHLAND
        | BURIAL_GROUNDS | THE_SECRET_COW_LEVEL => WILDERNESS_1,
        DEN_OF_EVIL
        | CAVE_LEVEL_1
        | CAVE_LEVEL_2
        | UNDERGROUND_PASSAGE_LEVEL_1
        | UNDERGROUND_PASSAGE_LEVEL_2
        | HOLE_LEVEL_1
        | HOLE_LEVEL_2
        | PIT_LEVEL_1
        | PIT_LEVEL_2 => CAVE_1,
        CRYPT_1 | MAUSOLEUM | FORGOTTEN_TOWER | TOWER_CELLAR_LEVEL_1 | TOWER_CELLAR_LEVEL_2
        | TOWER_CELLAR_LEVEL_3 | TOWER_CELLAR_LEVEL_4 | TOWER_CELLAR_LEVEL_5 => CRYPT_1,
        MONASTERY_GATE | OUTER_CLOISTER | BARRACKS | RUINED_TEMPLE | RUINED_FANE | DISUSED_FANE
        | DISUSED_RELIQUARY | FORGOTTEN_RELIQUARY | FORGOTTEN_TEMPLE => COURTYARD_1,
        JAIL_LEVEL_1 | JAIL_LEVEL_2 | JAIL_LEVEL_3 => JAIL_1,
        INNER_CLOISTER | CATHEDRAL => CATHEDRAL_1,
        CATACOMBS_LEVEL_1 | CATACOMBS_LEVEL_2 | CATACOMBS_LEVEL_3 | CATACOMBS_LEVEL_4 => {
            CATACOMBS_1
        }
        TRISTRAM => TRISTRAM_1,
        LUT_GHOLEIN => TOWN_2,
        ROCKY_WASTE | DRY_HILLS | FAR_OASIS | LOST_CITY | VALLEY_OF_SNAKES | CANYON_OF_THE_MAGI => {
            DESERT_2
        }
        SEWERS_LEVEL_1 | SEWERS_LEVEL_2 | SEWERS_LEVEL_3 | ANCIENT_TUNNELS => SEWER_2,
        HAREM_LEVEL_1
        | HAREM_LEVEL_2
        | PALACE_CELLAR_LEVEL_1
        | PALACE_CELLAR_LEVEL_2
        | PALACE_CELLAR_LEVEL_3 => HAREM_2,
        STONY_TOMB_LEVEL_1
        | STONY_TOMB_LEVEL_2
        | HALLS_OF_THE_DEAD_LEVEL_1
        | HALLS_OF_THE_DEAD_LEVEL_2
        | HALLS_OF_THE_DEAD_LEVEL_3
        | CLAW_VIPER_TEMPLE_LEVEL_1
        | CLAW_VIPER_TEMPLE_LEVEL_2
        | TAL_RASHA_S_TOMB
        | TAL_RASHA_S_CHAMBER => TOMB_2,
        MAGGOT_LAIR_LEVEL_1 | MAGGOT_LAIR_LEVEL_2 | MAGGOT_LAIR_LEVEL_3 => LAIR_2,
        ARCANE_SANCTUARY => ARCANE_2,
        KURAST_DOCKS => TOWN_3,
        SPIDER_FOREST | GREAT_MARSH | FLAYER_JUNGLE => JUNGLE_3,
        LOWER_KURAST | KURAST_BAZAAR | UPPER_KURAST | KURAST_CAUSEWAY | TRAVINCAL => KURAST_3,
        SPIDER_CAVE | SPIDER_CAVERN => SPIDER_3,
        SWAMPY_PIT_LEVEL_1
        | SWAMPY_PIT_LEVEL_2
        | SWAMPY_PIT_LEVEL_3
        | FLAYER_DUNGEON_LEVEL_1
        | FLAYER_DUNGEON_LEVEL_2
        | FLAYER_DUNGEON_LEVEL_3
        | DURANCE_OF_HATE_LEVEL_1
        | DURANCE_OF_HATE_LEVEL_2
        | DURANCE_OF_HATE_LEVEL_3 => DUNGEON_3,
        THE_PANDEMONIUM_FORTRESS => TOWN_4,
        OUTER_STEPPES | PLAINS_OF_DESPAIR | CITY_OF_THE_DAMNED => MESA_4,
        RIVER_OF_FLAME | THE_CHAOS_SANCTUARY => LAVA_4,
        BLOODY_FOOTHILLS | FRIGID_HIGHLANDS | ARREAT_PLATEAU | FROZEN_TUNDRA => BARRICADE_5,
        CRYSTALLINE_PASSAGE | FROZEN_RIVER | THE_ANCIENTS_WAY | GLACIAL_TRAIL | DRIFTER_CAVERN => {
            ICE_5
        }
        NIHLATHAKS_TEMPLE | HALLS_OF_PAIN | HALLS_OF_ANGUISH | HALLS_OF_VAUGHT => TEMPLE_5,
        ABADDON | PIT_OF_ACHERON | INFERNAL_PIT => LAVA_5,
        WORLDSTONE_KEEP_LEVEL_1
        | WORLDSTONE_KEEP_LEVEL_2
        | WORLDSTONE_KEEP_LEVEL_3
        | THRONE_OF_DESTRUCTION
        | WORLDSTONE_CHAMBER => BAAL_5,
        _ => panic!("Incorrect zone: '{zone}'"),
    }
    .to_string()
}
