[package]
name = "mpq_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adler32 = "1.2.0"
byteorder = "1.5.0"
bzip2-rs = "0.1.2"
flate2 = "1.0.30"
implode = "0.1.1"
