use super::belt_item_names::{
    GREATER_HEALING_POTION, GREATER_MANA_POTION, HEALING_POTION, LIGHT_HEALING_POTION,
    LIGHT_MANA_POTION, MANA_POTION, MINOR_HEALING_POTION, MINOR_MANA_POTION, SUPER_HEALING_POTION,
    SUPER_MANA_POTION,
};

pub const HEALING_POTION_RANKINGS: [(&str, i32); 5] = [
    (MINOR_HEALING_POTION, 0),
    (LIGHT_HEALING_POTION, 1),
    (HEALING_POTION, 2),
    (GREATER_HEALING_POTION, 3),
    (SUPER_HEALING_POTION, 4),
];

pub const MANA_POTION_RANKINGS: [(&str, i32); 5] = [
    (MINOR_MANA_POTION, 0),
    (LIGHT_MANA_POTION, 1),
    (MANA_POTION, 2),
    (GREATER_MANA_POTION, 3),
    (SUPER_MANA_POTION, 4),
];
