use super::belt_item_names::{
    FULL_REJUVENATION_POTION, GREATER_HEALING_POTION, GREATER_MANA_POTION, HEALING_POTION,
    LIGHT_HEALING_POTION, LIGHT_MANA_POTION, MANA_POTION, MINOR_HEALING_POTION, MINOR_MANA_POTION,
    REJUVENATION_POTION, SUPER_HEALING_POTION, SUPER_MANA_POTION,
};

pub const SORTED_POTION_NAMES: [&str; 12] = [
    FULL_REJUVENATION_POTION,
    REJUVENATION_POTION,
    SUPER_MANA_POTION,
    GREATER_MANA_POTION,
    MANA_POTION,
    LIGHT_MANA_POTION,
    MINOR_MANA_POTION,
    SUPER_HEALING_POTION,
    GREATER_HEALING_POTION,
    HEALING_POTION,
    LIGHT_HEALING_POTION,
    MINOR_HEALING_POTION,
];
